language: python
python: 2.7
virtualenv:
  system_site_packages: true
branches:
    only:
        - master
before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-base texlive-latex-extra texlive-latex-recommended
- sudo apt-get install python-pip python-dev
- sudo apt-get install cdo libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev
- sudo apt-get install python-numpy
- sudo C_INCLUDE_PATH=/usr/include/mpi pip install netCDF4
- sudo pip install cdo coveralls pytest-cov
- sudo pip install pyshp
- pushd .
- git clone https://github.com/SciTools/cartopy.git && cd cartopy
- sudo add-apt-repository -y ppa:pylab/stable
- sudo add-apt-repository -y ppa:tukss/ppa
- sudo apt-get update
- sudo apt-get install python-scipy python-pip cython
- sudo /usr/bin/pip install https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.1/matplotlib-1.3.1.tar.gz
- sudo apt-get install python-mpltoolkits.basemap python-mpltoolkits.basemap-data
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
- yes | sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update
- sudo apt-get install libgeos-dev libproj-dev
- sudo /usr/bin/pip install --use-mirrors shapely nose pyshp pep8 mock
- sudo /usr/bin/pip install --use-mirrors PIL
- sudo /usr/bin/python setup.py install
- popd
- sudo sh compile_extensions.sh
script:
- nosetests --with-coverage --cover-package=pycmbs
after_success:
- coveralls
deploy:
  provider: pypi
  user: pycmbs_devs
  password:
    secure: X5cSY/ZCdULBqtD8/fc+IvThpuYgaEEU28DM/84GyqQPrt0aURdckcyp16UwYoOm0C1EsnLJ91fAHxXpaQsbjdVCNRTX0btdq2pT8UwxQKGJJMYXENKsGZi035cPK1Y3he3db3kEKcZD/ys3uUcyp9zWdVUt/E8P9b8GqqOd/So=
  on:
    tags: true
    repo: pygeo/pycmbs
env:
    global:
    - secure: cN9qTk1NsSckHgksATMMdthrFPO9a/rl2F6MNPK3uvCfQui2sIottchC6MT7+2Z2bBaBQN7b3VJLOlSf8WNzNEvIXfQ3FP7hDHQ+w97qsGUAsAVSrF+JNvsC2vESj9A/CCkyr2rejtF9NWmk/Lgx/3YZDGsmeeMNJzCp5MKEY8k=
