language: python
python:
    2.7
install:
    - sudo apt-get update
    - sudo apt-get install python-matplotlib
    - sudo apt-get install python-numpy
    - sudo apt-get install libhdf5-serial-dev libnetcdf-dev
    - sudo pip install netCDF4
    - sudo pip install cdo
    - sudo pip install coveralls
    - sudo apt-get install python-scipy
script:
    nosetests
after_success:
    coveralls
