language: python
python:
    2.7
virtualenv:
    system_site_packages: true
before_install:
    - ./.travis_no_output sudo apt-get update
    - ./.travis_no_output sudo apt-get install python-matplotlib 
    - ./.travis_no_output sudo apt-get install python-mpltoolkits.basemap python-mpltoolkits.basemap-data
    - ./.travis_no_output sudo apt-get install python-numpy
    - ./.travis_no_output sudo apt-get install cdo
    - ./.travis_no_output sudo apt-get install libhdf5-serial-dev libnetcdf-dev
    - ./.travis_no_output sudo pip install netCDF4
    - ./.travis_no_output sudo pip install cdo
    - ./.travis_no_output sudo pip install coveralls
    - ./.travis_no_output sudo pip install pytest-cov
    - pushd .
    - git clone https://github.com/SciTools/cartopy.git && cd cartopy
    - sudo add-apt-repository -y ppa:pylab/stable
    - sudo add-apt-repository -y ppa:tukss/ppa
    - ./.travis_no_output sudo apt-get update
    - ./.travis_no_output sudo apt-get install python-scipy python-pip cython
    - ./.travis_no_output sudo /usr/bin/pip install https://downloads.sourceforge.net/project/matplotlib/matplotlib/matplotlib-1.3.1/matplotlib-1.3.1.tar.gz
    # http://www.webupd8.org/2010/10/fix-nopubkey-error-for-extras-ubuntu.html
    - ./.travis_no_output sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192
    - yes | ./.travis_no_output sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
    - ./.travis_no_output sudo apt-get update
    - ./.travis_no_output sudo apt-get install libgeos-dev libproj-dev
    - ./.travis_no_output sudo /usr/bin/pip install --use-mirrors shapely nose pyshp pep8 mock
    # its always version 2 currently
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then ./.travis_no_output sudo /usr/bin/pip install --use-mirrors PIL; fi
    # install cartopy in the .local directory (in lieu of using virtual env...)
    - ./.travis_no_output sudo /usr/bin/python setup.py install
    - popd

script:
    - nosetests --with-coverage --cover-package=pycmbs
after_success:
    - coveralls
