language: python
python:
    2.7
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update
    - sudo apt-get install python-matplotlib 
    - sudo apt-get install python-mpltoolkits.basemap python-mpltoolkits.basemap-data
    - sudo apt-get install python-numpy
    - sudo apt-get install cdo
    - sudo apt-get install libhdf5-serial-dev libnetcdf-dev
    - sudo pip install netCDF4
    - sudo pip install cdo
    - sudo pip install coveralls
    - sudo pip install pytest-cov
    - sudo apt-get install python-scipy
    - pushd .
    - git clone https://github.com/SciTools/cartopy.git && cd cartopy && sudo python setup.py install
    - popd
script:
    - nosetests --with-coverage --cover-package=pycmbs
after_success:
    - coveralls
