language: python
python: 2.7
virtualenv:
  system_site_packages: true
branches:
    only:
        - master
before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-base texlive-latex-extra texlive-latex-recommended
- sudo apt-get install python-pip python-dev
- sudo apt-get install cdo libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev
- sudo apt-get install python-numpy
- sudo apt-get install libgdal1h
- sudo apt-get install libgdal-dev
- sudo C_INCLUDE_PATH=/usr/include/mpi pip install netCDF4
- sudo pip install cdo coveralls pytest-cov
- sudo pip install pyshp
- sudo pip install matplotlib
- sudo pip install shapely
- sudo pip install cartopy
- sudo pip install cython
- sudo /usr/bin/python setup.py install
- sudo sh compile_extensions.sh
script:
- nosetests --with-coverage --cover-package=pycmbs
after_success:
- coveralls
deploy:
  provider: pypi
  user: pycmbs_devs
  password:
    secure: X5cSY/ZCdULBqtD8/fc+IvThpuYgaEEU28DM/84GyqQPrt0aURdckcyp16UwYoOm0C1EsnLJ91fAHxXpaQsbjdVCNRTX0btdq2pT8UwxQKGJJMYXENKsGZi035cPK1Y3he3db3kEKcZD/ys3uUcyp9zWdVUt/E8P9b8GqqOd/So=
  on:
    tags: true
    repo: pygeo/pycmbs
env:
    global:
    - secure: cN9qTk1NsSckHgksATMMdthrFPO9a/rl2F6MNPK3uvCfQui2sIottchC6MT7+2Z2bBaBQN7b3VJLOlSf8WNzNEvIXfQ3FP7hDHQ+w97qsGUAsAVSrF+JNvsC2vESj9A/CCkyr2rejtF9NWmk/Lgx/3YZDGsmeeMNJzCp5MKEY8k=




